---
abstract: 'DBI Backend for Deeme'
author:
  - 'mudler <mudler@dark-lab.net>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Deeme-Backend-DBI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/mudler/p5-Deeme-Backend-DBI/issues
  homepage: https://github.com/mudler/p5-Deeme-Backend-DBI
  repository: https://github.com/mudler/p5-Deeme-Backend-DBI.git
version: 0.01
